---
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes:
  - \usepackage[spanish]{babel}
---

# Capítulo III Marco Metódico \label{sec:cap III}

## Análisis Exploratorio de los datos

### Datos OHLC y Fuente de los datos

La estructura de los datos utilizados en el trabajo es de tipo OHLC por sus siglas en inglés Open, High, Low, Close. La misma agrega en 4 registros el comportamiento del precio del activo (Apertura, Cierre, Mínimo y Máximo) en un intervalo de tiempo, en el caso de la presente investigación, de un día. 

Este tipo de dato provee la información necesaria para cubrir las exigencia del modelo, tanto para la creación de la variable dependiente como para el cálculo de los indicadores técnicos

<!-- Hablar sobre Investing.com como fuente de datos -->

### Series a utilizar

El universo de estudio está representado por los índices bursátiles de los mercados financieros existentes entre el período (26/10/2008 - 18/01/2019). Un índice búrsatil es un promedio de los precios de los activos que representan un mercado o sector en concreto. La muestra está constituida por 5 índices bursátiles que representan distintos mercados del mundo: NASDAQ, NIKKEI, FTSE 100, BOVESPA y S&P500.

```{r}
library(tidyverse)
library(magrittr)
library(lubridate)
library(gridExtra)

serie <- c('S&P_500', 'NASDAQ', 'NIKKEI_225', 'FTSE_100', 'BOVESPA')
list_serie <- list()
for(s in serie){
  .aux_serie <- paste('data/', s, '.csv', sep = '') %>%
    read_csv(locale = locale(decimal_mark = ",", grouping_mark = ".")) %>%
    select(-one_of(c('Vol.', '% var.'))) %>% 
    mutate(Fecha = dmy(Fecha)) %>% 
    setNames(c('timestamp', 'close', 'open', 'high', 'low')) %>% 
    arrange(timestamp)
  
  list_serie %<>% rlist::list.append(.aux_serie) 
}

plot_serie <- list()
for(i in 1:5){
  .aux_plot <- list_serie[[i]] %>% 
    ggplot(aes(x = timestamp, y = close)) + 
    geom_line() + 
    labs(x = 'Fecha', y = 'Precio de Cierre', title = serie[i]) + 
    theme_minimal() +
    scale_y_continuous(labels = scales::number)
  
  plot_serie %<>% rlist::list.append(.aux_plot)
}

do.call('grid.arrange', plot_serie)
```


### Indicadores Técnicos como variables predictoras

Los indicadores a utilizar fueron seleccionados buscando recoger la mayor información posible sobre el precio del activo que se pueden resumir en tres categorías: tendencia, momentum y volatilidad.

<!-- Definir las 3 categorías -->

No es de interés en la presente investigación describir como funciona cada indicador para la toma de decisiones en el trading basado en fundamentos técnicos. Cada indicador puede utilizarse de distintas maneras, calcularse con distintos parámetros y asociarse a discreción del trader, lo que conlleva a un sin fin de reglas de asciación. 

Lo que busca la investigación es utilizar la relación entre estos indicadores como variables independientes que ayuden al modelo a predecir oportunidades de entradas. En este sentido se asume la existencia de una dinámica local del mercado que puede ser predecida con ayuda de estos indicadores.

## Entrenamiento del Modelo

### Variable dependiente

Las decisiones de entrada en el trading pueden ser producto de muchos factores, en la presente investigación se analiza el enfoque donde se define un porcentaje objetivo de ganancia y se intenta predecir si dicho objetivo se materializará en un futuro cercano. Este enfoque reduce la toma de decisión en una variable tal que:

$$
P_{X}(x) = 
\begin{array}{ll} 
\ \ \ \ p \ ; \qquad x = c
\\
\ 1-p \ ; \qquad x = -d
\end{array}
$$

Dado los datos OHLC del activo es posible identificar los períodos en donde se materializa la variable dependiente, es decir, que el precio alcanza un porcentaje de ganancia sin antes haber retrocedido un porcentaje fijo. 

Se añade una columna con 'buy' para identificar los registros donde se da la señal y 'stay' en caso de que no haya ocurrido o hubiese ocurrido primero el retroceso del precio.

### División de los datos en Entrenamiento, Validación y Prueba

Los datos son divididos en tres grupos: entrenamiento que representa 60% del total de los datos, validación y prueba, cada uno representando 20%. Los datos de entrenamiento son los que se utilizarán para enseñar al modelo a estimar la variable dependiente. Los datos de validación se utilizarán para definir la mejor combinación de parámetros (tp, sl y horizonte). Finalmente en los datos de prueba se aplica el modelo para obtener resultados simulando la estrategia.

### Reducción de la dimensión con Análisis de Componentes Principales

### Validación Cruzada en Series de Tiempo

### Selección de parámetros con mayor valor de predicción positiva

<!-- Hablar sobre matriz de confusion -->

En principio se desconoce cuales debieran ser los parámetros (tp, sl y horizonte) con los que opere la estrategia, para su estimación, se aplica el modelo entrenado en los primeren la data de validación y se obtiene para cada combinación de parametros definidos previamente, el valor de predicción positivo. Dado que la estrategia solo opera en largo, es de interés obtener el mayor porcentaje de acierto de los casos verdaderos positivos.

<!-- Grafica de seleccion de parametros e interpretar -->

## Prueba de modelos óptimos en los datos de validación
